version: "2"
services:
  influxgateway:
    build: .
    image: acrelle/influxgateway
    container_name: influxgateway
    restart: unless-stopped
    ports:
      - 9956:80
    environment:
      - influxconnectionsettings_influxusername=username
      - influxconnectionsettings_influxpassword=password
      - influxconnectionsettings_influxurl=http://127.0.0.1:8086
      - influxconnectionsettings_influxdatabase=database_name